# Generated by Django 5.1 on 2024-09-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instadb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
    ]
