# Generated by Django 5.1 on 2024-09-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadb', '0002_rename_user_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
