# Generated by Django 5.1 on 2024-09-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadb', '0005_remove_posts_image_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='description',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
