# Generated by Django 5.1 on 2024-09-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadb', '0008_posts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='liked_by_me',
            field=models.BooleanField(default=False),
        ),
    ]
