# Generated by Django 5.1 on 2024-09-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instadb', '0010_posts_likes_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='likes_count',
            new_name='total_likes',
        ),
    ]
