# Generated by Django 5.1 on 2024-09-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadb', '0012_alter_posts_total_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.CharField(default='', max_length=60),
        ),
    ]
