# Generated by Django 5.1 on 2024-09-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadb', '0013_alter_posts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='total_likes',
            field=models.IntegerField(default=5),
        ),
    ]
