# Generated by Django 5.1 on 2024-09-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadb', '0014_alter_posts_total_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment'},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name': 'Like'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['user_profile'], 'verbose_name': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
