# Generated by Django 5.1 on 2024-09-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instadb', '0015_alter_comments_options_alter_likes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
